# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=30)),
                ('edition', models.IntegerField()),
                ('dept', models.CharField(max_length=4)),
                ('class_number', models.IntegerField()),
                ('isbn', models.IntegerField()),
                ('price', models.IntegerField()),
                ('post_date', models.DateTimeField(verbose_name='date posted')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('payment', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stoBooks_app.Student'),
        ),
    ]
