# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-30 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stoBooks_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-post_date']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-username']},
        ),
        migrations.AddField(
            model_name='book',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='dept',
            field=models.CharField(choices=[('AFAM', 'AFAM'), ('AMCON', 'AMCON'), ('AMST', 'AMST'), ('ART', 'ART'), ('ASIAN', 'ASIAN'), ('BIO', 'BIO'), ('CH/BI', 'CH/BI'), ('CHEM', 'CHEM'), ('CHIN', 'CHIN'), ('CLASS', 'CLASS'), ('CSCI', 'CSCI'), ('DANCE', 'DANCE'), ('ECON', 'ECON'), ('EDUC', 'EDUC'), ('ENGL', 'ENGL'), ('ENVST', 'ENVST'), ('ESAC', 'ESAC'), ('ESTH', 'ESTH'), ('FAMST', 'FAMST'), ('FILM', 'FILM'), ('FREN', 'FREN'), ('GCON', 'GCON'), ('GERM', 'GERM'), ('GREEK', 'GREEK'), ('HIST', 'HIST'), ('ID', 'ID'), ('IS', 'IS'), ('JAPAN', 'JAPAN'), ('LATIN', 'LATIN'), ('MATH', 'MATH'), ('MEDIA', 'MEDIA'), ('MGMT', 'MGMT'), ('MSCS', 'MSCS'), ('MUSEN', 'MUSEN'), ('MUSIC', 'MUSIC'), ('NORW', 'NORW'), ('NURS', 'NURS'), ('OFFC', 'OFFC'), ('PACON', 'PACON'), ('PHIL', 'PHIL'), ('PHYS', 'PHYS'), ('PSCI', 'PSCI'), ('PSYCH', 'PSYCH'), ('RACE', 'RACE'), ('REL', 'REL'), ('RUSSN', 'RUSSN'), ('SCICN', 'SCICN'), ('SOAN', 'SOAN'), ('SPAN', 'SPAN'), ('STAT', 'STAT'), ('SWRK', 'SWRK'), ('THEAT', 'THEAT'), ('WMGST', 'WMGST'), ('WRIT', 'WRIT')], max_length=5),
        ),
        migrations.AlterField(
            model_name='book',
            name='post_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
