# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-30 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stoBooks_app', '0002_auto_20171230_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
